"""init: all tables of schema groups 1-6, triggers and seed data.

The table part is generated from the ORM models. The triggers, seed data
and ENUM type drops are written by hand (autogenerate cannot see them).

Revision ID: 0001
Revises:
Create Date: 2026-10-06 18:59:08.982828

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_name", sa.Text(), nullable=True),
        sa.Column("workspace_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=True),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column("target_label", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "action IN ('member_added', 'member_removed', 'role_added', 'role_removed', 'workspace_taken', 'made_public', 'archived', 'task_deleted', 'work_published', 'publisher_created', 'admin_granted', 'admin_revoked', 'user_deleted')",
            name="activity_events_action_check",
        ),
        sa.CheckConstraint(
            "target_type IN ('workspace', 'membership', 'task', 'work', 'publication', 'publisher', 'user')",
            name="activity_events_target_type_check",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("activity_events_pkey")),
    )
    op.create_index(
        "activity_events_workspace_occurred_idx",
        "activity_events",
        ["workspace_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_table(
        "auth_providers",
        sa.Column("id", sa.SmallInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("auth_providers_pkey")),
        sa.UniqueConstraint("name", name=op.f("auth_providers_name_key")),
    )
    op.create_table(
        "capabilities",
        sa.Column("id", sa.SmallInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("capabilities_pkey")),
        sa.UniqueConstraint("name", name=op.f("capabilities_name_key")),
    )
    op.create_table(
        "log_deletions",
        sa.Column("call_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("call_id", name=op.f("log_deletions_pkey")),
    )
    op.create_table(
        "model_providers",
        sa.Column("id", sa.SmallInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("adapter", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("secret_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "adapter IN ('ollama', 'openai_compatible', 'anthropic')",
            name="model_providers_adapter_check",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("model_providers_pkey")),
        sa.UniqueConstraint("name", name=op.f("model_providers_name_key")),
    )
    op.create_table(
        "pipelines",
        sa.Column("id", sa.SmallInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pipelines_pkey")),
        sa.UniqueConstraint("name", name=op.f("pipelines_name_key")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.SmallInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("roles_pkey")),
        sa.UniqueConstraint("name", name=op.f("roles_name_key")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("username", name=op.f("users_username_key")),
    )
    op.create_index(
        "users_email_lower_key", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "admins",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("admins_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("admins_pkey")),
    )
    op.create_table(
        "models",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("provider_id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("context_length", sa.Integer(), nullable=False),
        sa.Column("vram_mb", sa.Integer(), nullable=True),
        sa.Column("ram_mb", sa.Integer(), nullable=True),
        sa.Column("cost_per_1m_input", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("cost_per_1m_output", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("available", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("context_length > 0", name="models_context_length_check"),
        sa.CheckConstraint("cost_per_1m_input >= 0", name="models_cost_per_1m_input_check"),
        sa.CheckConstraint("cost_per_1m_output >= 0", name="models_cost_per_1m_output_check"),
        sa.CheckConstraint("ram_mb >= 0", name="models_ram_mb_check"),
        sa.CheckConstraint("vram_mb >= 0", name="models_vram_mb_check"),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["model_providers.id"],
            name=op.f("models_provider_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("models_pkey")),
        sa.UniqueConstraint("provider_id", "name", name=op.f("models_provider_id_name_key")),
    )
    op.create_table(
        "password_credentials",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("password_credentials_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("password_credentials_pkey")),
    )
    op.create_table(
        "pipeline_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("pipeline_id", sa.SmallInteger(), nullable=False),
        sa.Column("version_name", sa.Text(), nullable=False),
        sa.Column("version_code", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version_code > 0", name="pipeline_versions_version_code_check"),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("pipeline_versions_pipeline_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pipeline_versions_pkey")),
        sa.UniqueConstraint(
            "pipeline_id",
            "version_code",
            name=op.f("pipeline_versions_pipeline_id_version_code_key"),
        ),
        sa.UniqueConstraint(
            "pipeline_id",
            "version_name",
            name=op.f("pipeline_versions_pipeline_id_version_name_key"),
        ),
    )
    op.create_table(
        "publishers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("publishers_owner_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("publishers_pkey")),
        sa.UniqueConstraint("name", name=op.f("publishers_name_key")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("expires_at > created_at", name="sessions_check"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("sessions_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
        sa.UniqueConstraint("refresh_token_hash", name=op.f("sessions_refresh_token_hash_key")),
    )
    op.create_index(op.f("sessions_user_id_idx"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_identities",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider_id", sa.SmallInteger(), nullable=False),
        sa.Column("provider_user_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["auth_providers.id"],
            name=op.f("user_identities_provider_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_identities_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_identities_pkey")),
        sa.UniqueConstraint(
            "provider_id",
            "provider_user_id",
            name=op.f("user_identities_provider_id_provider_user_id_key"),
        ),
    )
    op.create_index(
        op.f("user_identities_user_id_idx"), "user_identities", ["user_id"], unique=False
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("private", "public", name="workspace_visibility"),
            server_default=sa.text("'private'"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("workspaces_created_by_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("workspaces_owner_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("workspaces_pkey")),
    )
    op.create_index(op.f("workspaces_owner_id_idx"), "workspaces", ["owner_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("workspace_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("memberships_role_id_fkey"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("memberships_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("memberships_workspace_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workspace_id", "user_id", "role_id", name=op.f("memberships_pkey")
        ),
    )
    op.create_index(op.f("memberships_user_id_idx"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "model_capabilities",
        sa.Column("model_id", sa.BigInteger(), nullable=False),
        sa.Column("capability_id", sa.SmallInteger(), nullable=False),
        sa.Column("kind", sa.Enum("strength", "weakness", name="capability_kind"), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("model_capabilities_capability_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("model_capabilities_model_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("model_id", "capability_id", name=op.f("model_capabilities_pkey")),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("workspace_id", sa.BigInteger(), nullable=False),
        sa.Column("pipeline_version_id", sa.BigInteger(), nullable=False),
        sa.Column("model_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "queued", "running", "in_review", "done", "cancelled", name="task_status"
            ),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("reviewer_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("tasks_created_by_fkey"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("tasks_model_id_fkey"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_version_id"],
            ["pipeline_versions.id"],
            name=op.f("tasks_pipeline_version_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("tasks_reviewer_id_fkey"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("tasks_workspace_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tasks_pkey")),
    )
    op.create_index(
        "tasks_active_status_idx",
        "tasks",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "tasks_in_review_reviewer_idx",
        "tasks",
        ["reviewer_id"],
        unique=False,
        postgresql_where=sa.text("status = 'in_review'"),
    )
    op.create_index(
        "tasks_workspace_created_idx",
        "tasks",
        ["workspace_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "task_reviews",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("reviewer_id", sa.BigInteger(), nullable=True),
        sa.Column("result", sa.Enum("accepted", "rejected", name="review_result"), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("result = 'accepted' OR comment IS NOT NULL", name="task_reviews_check"),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("task_reviews_reviewer_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("task_reviews_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("task_reviews_pkey")),
    )
    op.create_index(op.f("task_reviews_task_id_idx"), "task_reviews", ["task_id"], unique=False)
    op.create_table(
        "works",
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("works_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("works_pkey")),
    )
    op.create_table(
        "publications",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("work_id", sa.BigInteger(), nullable=False),
        sa.Column("publisher_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["publishers.id"],
            name=op.f("publications_publisher_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.task_id"],
            name=op.f("publications_work_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("publications_pkey")),
        sa.UniqueConstraint("work_id", name=op.f("publications_work_id_key")),
    )
    op.create_index(
        "publications_publisher_published_idx",
        "publications",
        ["publisher_id", sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_table(
        "task_steps",
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("step_index", sa.SmallInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "done", name="task_step_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("review_id", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("step_index >= 0", name="task_steps_step_index_check"),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["task_reviews.id"],
            name=op.f("task_steps_review_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("task_steps_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("task_id", "step_index", name=op.f("task_steps_pkey")),
    )
    op.create_index(op.f("task_steps_review_id_idx"), "task_steps", ["review_id"], unique=False)
    op.create_table(
        "work_sources",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("work_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("kind", sa.Enum("web", "file", name="source_kind"), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.task_id"],
            name=op.f("work_sources_work_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("work_sources_pkey")),
        sa.UniqueConstraint("work_id", "location", name=op.f("work_sources_work_id_location_key")),
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("step_index", sa.SmallInteger(), nullable=False),
        sa.Column("model_id", sa.BigInteger(), nullable=False),
        sa.Column("attempt", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "done", "failed", "cancelled", name="llm_call_status"),
            server_default=sa.text("'queued'"),
            nullable=False,
        ),
        sa.Column("response_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("attempt >= 1", name="llm_calls_attempt_check"),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("llm_calls_model_id_fkey"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "step_index"],
            ["task_steps.task_id", "task_steps.step_index"],
            name=op.f("llm_calls_task_id_step_index_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("llm_calls_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("llm_calls_pkey")),
    )
    op.create_index("llm_calls_task_step_idx", "llm_calls", ["task_id", "step_index"], unique=False)
    op.create_table(
        "quotes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("work_source_id", sa.BigInteger(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("placement", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["work_source_id"],
            ["work_sources.id"],
            name=op.f("quotes_work_source_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("quotes_pkey")),
    )
    op.create_index(op.f("quotes_work_source_id_idx"), "quotes", ["work_source_id"], unique=False)
    op.create_table(
        "llm_responses",
        sa.Column("call_id", sa.BigInteger(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "finish_reason", sa.Enum("stop", "length", "other", name="finish_reason"), nullable=True
        ),
        sa.Column("valid_json", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("input_tokens >= 0", name="llm_responses_input_tokens_check"),
        sa.CheckConstraint("output_tokens >= 0", name="llm_responses_output_tokens_check"),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["llm_calls.id"],
            name=op.f("llm_responses_call_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("call_id", name=op.f("llm_responses_pkey")),
    )
    # ### end Alembic commands ###

    create_triggers()
    insert_seed_data()


def create_triggers() -> None:
    # Public once, public forever. A CHECK cannot see the old value.
    op.execute("""
        CREATE FUNCTION workspaces_keep_public() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.visibility = 'public' AND NEW.visibility <> 'public' THEN
                RAISE EXCEPTION 'workspace % is public and cannot become private', OLD.id;
            END IF;
            RETURN NEW;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER workspaces_keep_public
            BEFORE UPDATE OF visibility ON workspaces
            FOR EACH ROW EXECUTE FUNCTION workspaces_keep_public()
    """)

    # Outbox for the log cleanup worker. Fires for direct deletes and for
    # CASCADE from tasks.
    op.execute("""
        CREATE FUNCTION llm_calls_queue_log_deletion() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            INSERT INTO log_deletions (call_id) VALUES (OLD.id)
            ON CONFLICT (call_id) DO NOTHING;
            RETURN OLD;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER llm_calls_queue_log_deletion
            BEFORE DELETE ON llm_calls
            FOR EACH ROW EXECUTE FUNCTION llm_calls_queue_log_deletion()
    """)


def insert_seed_data() -> None:
    op.execute("""
        INSERT INTO roles (name, description) VALUES
            ('editor',   'Can create and edit tasks'),
            ('reviewer', 'Can review results'),
            ('viewer',   'Can only read')
    """)
    op.execute("""
        INSERT INTO model_providers (name, adapter, base_url) VALUES
            ('ollama', 'ollama', 'http://localhost:11434')
    """)
    op.execute("""
        INSERT INTO capabilities (name, description) VALUES
            ('json_output', 'Returns valid JSON for a given schema'),
            ('summarize',   'Summarizes a text')
    """)
    op.execute("""
        INSERT INTO pipelines (name, description) VALUES
            ('research',         'Any topic, with search and verification'),
            ('opinion_survey',   'What sources say about a topic'),
            ('study_notes',      'Notes on a topic, search is optional'),
            ('creative_writing', 'Creative text, no search, no verification')
    """)
    op.execute("""
        INSERT INTO auth_providers (name) VALUES ('github'), ('google')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_responses")
    op.drop_index(op.f("quotes_work_source_id_idx"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index("llm_calls_task_step_idx", table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_table("work_sources")
    op.drop_index(op.f("task_steps_review_id_idx"), table_name="task_steps")
    op.drop_table("task_steps")
    op.drop_index("publications_publisher_published_idx", table_name="publications")
    op.drop_table("publications")
    op.drop_table("works")
    op.drop_index(op.f("task_reviews_task_id_idx"), table_name="task_reviews")
    op.drop_table("task_reviews")
    op.drop_index("tasks_workspace_created_idx", table_name="tasks")
    op.drop_index(
        "tasks_in_review_reviewer_idx",
        table_name="tasks",
        postgresql_where=sa.text("status = 'in_review'"),
    )
    op.drop_index(
        "tasks_active_status_idx",
        table_name="tasks",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_table("tasks")
    op.drop_table("model_capabilities")
    op.drop_index(op.f("memberships_user_id_idx"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("workspaces_owner_id_idx"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("user_identities_user_id_idx"), table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_index(op.f("sessions_user_id_idx"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("publishers")
    op.drop_table("pipeline_versions")
    op.drop_table("password_credentials")
    op.drop_table("models")
    op.drop_table("admins")
    op.drop_index("users_email_lower_key", table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("pipelines")
    op.drop_table("model_providers")
    op.drop_table("log_deletions")
    op.drop_table("capabilities")
    op.drop_table("auth_providers")
    op.drop_index("activity_events_workspace_occurred_idx", table_name="activity_events")
    op.drop_table("activity_events")
    # ### end Alembic commands ###

    # Dropping a table drops its triggers, but not the functions and not
    # the ENUM types.
    op.execute("DROP FUNCTION workspaces_keep_public()")
    op.execute("DROP FUNCTION llm_calls_queue_log_deletion()")
    for enum_name in (
        "workspace_visibility",
        "capability_kind",
        "task_status",
        "task_step_status",
        "llm_call_status",
        "finish_reason",
        "source_kind",
        "review_result",
    ):
        op.execute(f"DROP TYPE {enum_name}")
