"""failed task status and workspace files

- task_status: new value 'failed' (final, like 'cancelled').
- New table workspace_files: user files copied into the workspace folder.
- activity_events: actions 'file_added', 'file_removed'; target 'file'.

The table is generated from the models; the enum value and the CHECK
changes are written by hand (autogenerate does not see them).

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07 00:03:29.172170

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

OLD_ACTIONS = (
    "member_added",
    "member_removed",
    "role_added",
    "role_removed",
    "workspace_taken",
    "made_public",
    "archived",
    "task_deleted",
    "work_published",
    "publisher_created",
    "admin_granted",
    "admin_revoked",
    "user_deleted",
    "unarchived",
    "workspace_deleted",
)
NEW_ACTIONS = OLD_ACTIONS + ("file_added", "file_removed")
OLD_TARGETS = ("workspace", "membership", "task", "work", "publication", "publisher", "user")
NEW_TARGETS = OLD_TARGETS + ("file",)
OLD_TASK_STATUSES = ("draft", "queued", "running", "in_review", "done", "cancelled")

# Partial indexes on tasks.status: they must be dropped while the column
# type is replaced on downgrade.
TASK_STATUS_INDEXES = {
    "tasks_active_status_idx": "(status) WHERE status IN ('queued', 'running')",
    "tasks_in_review_reviewer_idx": "(reviewer_id) WHERE status = 'in_review'",
}


def in_list(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{v}'" for v in values)


def set_checks(actions: tuple[str, ...], targets: tuple[str, ...]) -> None:
    for name, column, values in (
        ("activity_events_action_check", "action", actions),
        ("activity_events_target_type_check", "target_type", targets),
    ):
        op.drop_constraint(name, "activity_events", type_="check")
        op.create_check_constraint(name, "activity_events", f"{column} IN ({in_list(values)})")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_files",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("workspace_id", sa.BigInteger(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=False),
        sa.Column("original_path", sa.Text(), nullable=True),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes >= 0", name="workspace_files_size_bytes_check"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("workspace_files_uploaded_by_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("workspace_files_workspace_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("workspace_files_pkey")),
        sa.UniqueConstraint(
            "workspace_id", "file_name", name=op.f("workspace_files_workspace_id_file_name_key")
        ),
    )
    # ### end Alembic commands ###

    op.execute("ALTER TYPE task_status ADD VALUE 'failed' AFTER 'cancelled'")
    set_checks(NEW_ACTIONS, NEW_TARGETS)


def downgrade() -> None:
    """Fails if activity events with the new actions exist: delete them
    first. Failed tasks become cancelled."""
    set_checks(OLD_ACTIONS, OLD_TARGETS)

    # PostgreSQL cannot remove an enum value: build the old type again.
    op.execute("UPDATE tasks SET status = 'cancelled' WHERE status = 'failed'")
    for name in TASK_STATUS_INDEXES:
        op.execute(f"DROP INDEX {name}")
    op.execute("ALTER TABLE tasks ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TYPE task_status RENAME TO task_status_old")
    op.execute(f"CREATE TYPE task_status AS ENUM ({in_list(OLD_TASK_STATUSES)})")
    op.execute(
        "ALTER TABLE tasks ALTER COLUMN status TYPE task_status USING status::text::task_status"
    )
    op.execute("ALTER TABLE tasks ALTER COLUMN status SET DEFAULT 'draft'")
    op.execute("DROP TYPE task_status_old")
    for name, definition in TASK_STATUS_INDEXES.items():
        op.execute(f"CREATE INDEX {name} ON tasks {definition}")

    op.drop_table("workspace_files")
